// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzzvtlxzkmdjvrwjatpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6enZ0bHh6a21kanZyd2phdHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTc1MTksImV4cCI6MjA3MjMzMzUxOX0.7XlZxqU4u--9RhpukrxGuS9UskfgD2KAo2YhVPFxZE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});